equivalencias <- c(
  "Universidad de Buenos Aires" = "Universidad de Buenos Aires",
  "Universidad de Buenos Aires (UBA)" = "Universidad de Buenos Aires",
  "UBA" = "Universidad de Buenos Aires",
  "Facultad de Psicología- Universidad de Buenos Aires" = "Universidad de Buenos Aires",
  "University of Buenos Aires" = "Universidad de Buenos Aires",
  "Universidad de Buenos Aires (Argentina)" = "Universidad de Buenos Aires",
  "Universidad de Buenos Aires / Instituto de Investigaciones Gino Germani" = "Universidad de Buenos Aires",
  "Faculty of Psychology of the University of Buenos Aires" = "Universidad de Buenos Aires",
  "Facultad de Ciencias Sociales. Universidad de Buenos Aires. Instituto de Investigaciones Gino Germani." = "Universidad de Buenos Aires",
  "Instituto de Investigaciones Gino Germani (IIGG) — Facultad de Ciencias Sociales (FSOC) — Universidad de Buenos Aires (UBA)" = "Universidad de Buenos Aires",
  "INEBA-CONICET. Facultad de Psicología de la Universidad de Buenos Aires." = "Universidad de Buenos Aires",
  "Faculty of Psychology of the University of Buenos Aires (UBA) National Council for Scientific and Technical Research (CONICET)" = "Universidad de Buenos Aires",
  "Instituto de Investigaciones - Facultad de Psicología - Universidad de Buenos Aires" = "Universidad de Buenos Aires",
  "CONICET" = "CONICET",
  "CONICET/Facultad de Psicología" = "CONICET",
  "INEBA-CONICET." = "CONICET",
  "CONICET- UNSAM (CELES)" = "CONICET",
  "CONICET y UNIVERSIDAD NACIONAL DE CÓRDOBA" = "CONICET",
  "CONICET / Universidad de Buenos Aires" = "CONICET",
  "Universidad de Buenos Aires (UBA) / CONICET" = "CONICET",
  "Universidad de Buenos Aires - CONICET" = "CONICET",
  "Universidad de Buenos Aires - Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET)" = "CONICET",
  "Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET) Escuela Interdisciplinaria de Altos Estudios Sociales (EIDAES)" = "CONICET",
  "University of Flores" = "Universidad de Flores",
  "Universidad de Flores" = "Universidad de Flores",
  "Universidad de Flores (UFLO)" = "Universidad de Flores",
  "USAL / Universidad de Flores UFLO" = "Universidad de Flores",
  "Universidad Maimónides" = "Universidad Maimónides",
  "Universidad Maimonides" = "Universidad Maimónides",
  "Universidad Maimónides (UM)" = "Universidad Maimónides",
  "Chile" = "NA",
  "Perú" = "NA",
  "NA" = "NA",
  "Argentina" = "NA",
  "Valencia (España)" = "NA",
  "Escuela de Psicología" = "NA",
  "España" = "NA",
  "Facultad de Psicología" = "NA",
  "Carrera de Psicología" = "NA",
  "Carrera de Trabajo Social" = "NA",
  "Castellón (España)." = "NA",
  "Cuba" = "NA",
  "Estados Unidos" = "NA",
  "Facultad de Economía y Negocios" = "NA",
  "Facultad de Educación" = "NA",
  "Facultad de Educación y Ciencias Sociales" = "NA",
  "Facultad de Humanidades" = "NA",
  "Universidad Católica Silva Henríquez" = "Universidad Católica Silva Henríquez",
  "Universidad Católica Silva Henríquez (UCSH)" = "Universidad Católica Silva Henríquez",
  "Universidad Católica Silva Henríquez (UCSH)
Universidad CatUniversidad Andrés Bello (UNAB)" = "Universidad Católica Silva Henríquez",
  "Barcelona" = "Universidad de Barcelona",
  "Universidad de Barcelona" = "Universidad de Barcelona",
  "Carrera de Psicología" = "Carrera de Trabajo
Social",
  "Carrera de Trabajo
Social" = "Carrera de Trabajo
Social",
  "Carrera de Trabajo Social" = "Carrera de Trabajo
Social",
  "Universidad Andrés Bello" = "Universidad Andrés Bello",
  "Universidad Andres Bello" = "Universidad Andrés Bello",
  "Universidad Andres Bello." = "Universidad Andrés Bello",
  "Universidad Católica Silva Henríquez (UCSH)
Universidad CatUniversidad Andrés Bello (UNAB)" = "Universidad Andrés Bello",
  "Belgium" = "NA",
  "Carrera de Psicología" = "NA",
  "Carrera de Trabajo
Social" = "NA",
  "Carrera de Trabajo Social" = "NA",
  "Carrera de Trabajo
Social" = "NA",
  "UBA" = "Universidad de Buenos Aires",
  "Facultad de Psicología - UBA" = "Universidad de Buenos Aires",
  "Universidad de Buenos Aires (UBA)" = "Universidad de Buenos Aires",
  "Facultad de Ciencias Sociales- UBA" = "Universidad de Buenos Aires",
  "Universidad de Buenos Aires (UBA) / CONICET" = "Universidad de Buenos Aires",
  "Instituto de Investigaciones Gino Germani (IIGG) — Facultad de Ciencias Sociales (FSOC) — Universidad de Buenos Aires (UBA)" = "Universidad de Buenos Aires",
  "Faculty of Psychology of the University of Buenos Aires (UBA)
National Council for Scientific and Technical Research (CONICET)" = "Universidad de Buenos Aires",
  "Faculty of Psychology of the University of Buenos Aires (UBA) National Council for Scientific and Technical Research (CONICET)" = "Universidad de Buenos Aires",
  "Universidad Abierta Interamericana (UAI" = "Universidad Abierta Interamericana",
  "Universidad Abierta Interamericana (UAI)" = "Universidad Abierta Interamericana",
  "CONICET" = "CONICET",
  "CONICET- UNSAM (CELES)" = "CONICET",
  "INEBA-CONICET. Facultad de Psicología de la Universidad de Buenos Aires." = "CONICET",
  "Universidad de Buenos Aires - Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET)" = "CONICET",
  "Faculty of Psychology of the University of Buenos Aires (UBA) National Council for Scientific and Technical Research (CONICET)" = "CONICET",
  "Faculty of Psychology of the University of Buenos Aires (UBA)
National Council for Scientific and Technical Research (CONICET)" = "CONICET",
  "CONICET/Facultad de Psicología" = "CONICET",
  "CONICET / Universidad de Buenos Aires" = "CONICET",
  "CONICET y UNIVERSIDAD NACIONAL DE CÓRDOBA" = "CONICET",
  "CONICET y  UNIVERSIDAD NACIONAL DE CÓRDOBA" = "CONICET",
  "INEBA-CONICET." = "CONICET",
  "Universidad de Buenos Aires - CONICET" = "CONICET",
  "Universidad de Buenos Aires (UBA) / CONICET" = "CONICET",
  "INEBA-CONICET.
Facultad de Psicología de la Universidad de Buenos Aires." = "CONICET",
  "Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET)
Escuela Interdisciplinaria de Altos Estudios Sociales (EIDAES)" = "CONICET",
  "Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET) Escuela Interdisciplinaria de Altos Estudios Sociales (EIDAES)" = "CONICET",
  "Consejo Nacional de Investigaciones Científicas y Técnicas" = "CONICET",
  "Consejo Nacional de Investigaciones Científicas y Técnicas UNIPE" = "CONICET",
  "Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET) Escuela Interdisciplinaria de Altos Estudios Sociales (EIDAES)" = "CONICET",
  "Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET)
Escuela Interdisciplinaria de Altos Estudios Sociales (EIDAES)" = "CONICET",
  "Universidad de Buenos Aires - Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET)" = "CONICET",
  "Universidad Abierta Interamericana" = "Universidad Abierta Interamericana",
  "Universidad Abierta Interamericana (UAI" = "Universidad Abierta Interamericana",
  "Universidad Abierta Interamericana (UAI)" = "Universidad Abierta Interamericana",
  "Universidad de Buenos Aires / Instituto de
Investigaciones Gino Germani" = "Universidad de Buenos Aires",
  "Universidad de Buenos Aires / Instituto de Investigaciones Gino Germani" = "Universidad de Buenos Aires",
  "Facultad de Ciencias Sociales. Universidad de Buenos Aires.
Instituto de Investigaciones Gino Germani." = "Universidad de Buenos Aires",
  "Facultad de Ciencias Sociales. Universidad de Buenos Aires. Instituto de Investigaciones Gino Germani." = "Universidad de Buenos Aires",
  "Instituto de Investigaciones Gino Germani (IIGG) — Facultad de Ciencias Sociales (FSOC) — Universidad de Buenos Aires (UBA)" = "Universidad de Buenos Aires",
  "Faculty of Psychology of the University of Buenos Aires (UBA) National Council for Scientific and Technical Research (CONICET)" = "Universidad de Buenos Aires",
  "Faculty of Psychology of the University of Buenos Aires (UBA)
National Council for Scientific and Technical Research (CONICET)" = "Universidad de Buenos Aires",
  "CONICET- UNSAM (CELES)" = "CONICET",
  "Universidad de Buenos Aires - Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET)" = "CONICET",
  "INEBA-CONICET." = "CONICET",
  "INEBA-CONICET.
Facultad de Psicología de la Universidad de Buenos Aires." = "CONICET",
  "INEBA-CONICET. Facultad de Psicología de la Universidad de Buenos Aires." = "CONICET",
  "INEBA-CONICET.
Facultad de Psicología de la Universidad de Buenos Aires." = "CONICET",
  "Universidad Católica Silva Henríquez" = "Universidad Católica Silva Henríquez",
  "Universidad Católica Silva Henríquez (UCSH)" = "Universidad Católica Silva Henríquez",
  "Universidad Católica Silva Henríquez (UCSH)
Universidad CatUniversidad Andrés Bello (UNAB)" = "Universidad Católica Silva Henríquez",
  "Universidad Católica Silva Henríquez (UCSH)
Universidad CatUniversidad Andrés Bello (UNAB)" = "Universidad Católica Silva Henríquez"
)